export { InvarianceTracer } from './tracer.js';
export type {
  TracerConfig,
  TracerMode,
  TraceEvent,
  TraceMetadata,
  BehavioralPrimitive,
  SemanticTraceSchemaVersion,
  DependencyEvidence,
  ContextInputKind,
  DependencyRelation,
  ContextInputReference,
  DependencyEdge,
  DependencyContextSummary,
  DevOutput,
  DecisionPointPayload,
  GoalDriftPayload,
  SubAgentSpawnPayload,
  ToolInvocationPayload,
  RetrievalEventPayload,
  OutputGenerationPayload,
  VerificationProof,
  TraceAction,
  ReplaySnapshot,
  ReplayTimelineEntry,
  ReplayContextMode,
  CounterfactualRequest,
  CounterfactualResult,
} from './types.js';
export { SEMANTIC_TRACE_SCHEMA_VERSION } from './types.js';
