export { InvarianceTracer } from './tracer.js';
export type {
  TracerConfig,
  TracerMode,
  TraceEvent,
  TraceMetadata,
  BehavioralPrimitive,
  DevOutput,
  DecisionPointPayload,
  GoalDriftPayload,
  SubAgentSpawnPayload,
  ToolInvocationPayload,
  VerificationProof,
  TraceAction,
  ReplaySnapshot,
  ReplayTimelineEntry,
  ReplayContextMode,
  CounterfactualRequest,
  CounterfactualResult,
} from './types.js';
