import type { HttpClient } from '../http.js';

import { IdentityResource } from '../resources/identity.js';
import { AgentsResource } from '../resources/agents.js';
import { SessionsResource } from '../resources/sessions.js';
import { ReceiptsResource } from '../resources/receipts.js';
import { ContractsResource } from '../resources/contracts.js';
import { A2AResource } from '../resources/a2a.js';
import { TraceResource } from '../resources/trace.js';
import { QueryResource } from '../resources/query.js';
import { MonitorsResource } from '../resources/monitors.js';
import { SignalsResource } from '../resources/signals.js';
import { DriftResource } from '../resources/drift.js';
import { TrainingResource } from '../resources/training.js';
import { TemplatesResource } from '../resources/templates.js';
import { ApiKeysResource } from '../resources/api-keys.js';
import { UsageResource } from '../resources/usage.js';
import { SearchResource } from '../resources/search.js';
import { StatusResource } from '../resources/status.js';
import { NLQueryResource } from '../resources/nl-query.js';
import { IdentitiesResource } from '../resources/identities.js';
import { EvalsResource } from '../resources/evals.js';
import { FailureClustersResource } from '../resources/failure-clusters.js';
import { SuggestionsResource } from '../resources/suggestions.js';
import { DocsResource } from '../resources/docs.js';
import { DatasetsResource } from '../resources/datasets.js';
import { ScorersResource } from '../resources/scorers.js';
import { ExperimentsResource } from '../resources/experiments.js';
import { PromptsResource } from '../resources/prompts.js';
import { AnnotationsResource } from '../resources/annotations.js';

export class ResourcesModule {
  readonly identity: IdentityResource;
  readonly agents: AgentsResource;
  readonly sessions: SessionsResource;
  readonly receipts: ReceiptsResource;
  readonly contracts: ContractsResource;
  readonly a2a: A2AResource;
  readonly trace: TraceResource;
  readonly query: QueryResource;
  readonly monitors: MonitorsResource;
  readonly signals: SignalsResource;
  readonly drift: DriftResource;
  readonly training: TrainingResource;
  readonly templates: TemplatesResource;
  readonly apiKeys: ApiKeysResource;
  readonly usage: UsageResource;
  readonly search: SearchResource;
  readonly status: StatusResource;
  readonly nlQuery: NLQueryResource;
  readonly identities: IdentitiesResource;
  readonly evals: EvalsResource;
  readonly failureClusters: FailureClustersResource;
  readonly suggestions: SuggestionsResource;
  readonly docs: DocsResource;
  readonly datasets: DatasetsResource;
  readonly scorers: ScorersResource;
  readonly experiments: ExperimentsResource;
  readonly prompts: PromptsResource;
  readonly annotations: AnnotationsResource;

  constructor(http: HttpClient) {
    this.identity = new IdentityResource(http);
    this.agents = new AgentsResource(http);
    this.sessions = new SessionsResource(http);
    this.receipts = new ReceiptsResource(http);
    this.contracts = new ContractsResource(http);
    this.a2a = new A2AResource(http);
    this.trace = new TraceResource(http);
    this.query = new QueryResource(http);
    this.monitors = new MonitorsResource(http);
    this.signals = new SignalsResource(http);
    this.drift = new DriftResource(http);
    this.training = new TrainingResource(http);
    this.templates = new TemplatesResource(http);
    this.apiKeys = new ApiKeysResource(http);
    this.usage = new UsageResource(http);
    this.search = new SearchResource(http);
    this.status = new StatusResource(http);
    this.nlQuery = new NLQueryResource(http);
    this.identities = new IdentitiesResource(http);
    this.evals = new EvalsResource(http);
    this.failureClusters = new FailureClustersResource(http);
    this.suggestions = new SuggestionsResource(http);
    this.docs = new DocsResource(http);
    this.datasets = new DatasetsResource(http);
    this.scorers = new ScorersResource(http);
    this.experiments = new ExperimentsResource(http);
    this.prompts = new PromptsResource(http);
    this.annotations = new AnnotationsResource(http);
  }
}
